server:
  port: 8082

spring:
  config:
    import: "optional:classpath:keys.properties"
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

whatsapp:
  apiUrl: https://graph.facebook.com/v15.0/
  apiToken: ${yours.token}
  webhookVerifyToken: ${your.webToken}
  phoneNumberId: ${phone.Id}

email:
  fromAddress: no-reply@sanifu.com
  allowedDomains: gmail.com,outlook.com,yahoo.com

ocr:
  dataPath: /usr/share/tesseract-ocr/4.00/tessdata
  language: eng

logging:
  level:
    root: INFO
    com.sanifu: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  order:
    processing:
      max-retries: 3
    confirmation:
      enable-pdf: true